/* =====================================================
   ESPANHOL — a terceira língua do lado do cliente (pedido da Milla:
   "Línguas: en / port / esp").

   A base (EmRoma) só tinha português e inglês. Aqui entra o espanhol de
   cada frase das telas do cliente: 536 reaproveitadas do app antigo da Yalla
   (onde o português não mudou) e as novas da base, traduzidas em 01/10/2026.
   Frase sem espanhol cai no inglês (t() em i18n.js). O painel dela segue
   em português.

   Carrega DEPOIS de i18n.js.
   ===================================================== */
'use strict';

const STR_ES = {
"aboutBased": "Vivo en",
"aboutCta": "Ver mis tours",
"aboutLangs": "Portugués · Inglés",
"aboutLink": "Quién soy",
"aboutLinkSub": "Quién te va a guiar",
"aboutMeet": "¿Caminamos juntos?",
"aboutMeetSub": "Elige una fecha y te espero en el punto de encuentro.",
"aboutSaved": "Tu página se actualizó",
"aboutTalk": "Escríbeme por WhatsApp",
"aboutTitle": "Hola, soy {guia}",
"addCal": "Añadir a mi calendario",
"addRule": "Añadir repetición",
"admAbout": "Tu foto y tu historia",
"admAboutHelp": "Esto es lo que aparece en “Quién soy”. Quien ve la cara de su guía reserva más — y cancela menos.",
"admAgenda": "Agenda",
"admAviso": "Aviso de nueva reserva",
"admAvisoBad": "Esto no parece un correo electrónico",
"admAvisoHelp": "Cuando alguien reserve por el sitio, te llega aquí un correo con el tour, la fecha, cuántas personas y el contacto. Basta con responder el correo y la respuesta va directo al cliente.",
"admAvisoMail": "Tu correo",
"admAvisoNota": "El aviso se revisa cada media hora, no en el momento exacto de la reserva. La reserva en sí aparece en el panel al instante.",
"admAvisoSaved": "Correo de aviso guardado",
"admBadge": "Tu credencial",
"admBase": "Dónde vives",
"admBio": "Tu texto",
"admBioHelp": "Escribe como hablas. Una línea en blanco separa los párrafos.",
"admBookings": "Reservas",
"admCard": "Aceptar tarjeta (Stripe)",
"admCardHelp": "El cliente paga con tarjeta al momento, directo a tu cuenta Stripe. La app calcula el importe sola y registra el pago cuando se acredita.",
"admCardNota": "La tarjeta no pasa por la app: el cliente paga en la página de Stripe. No guardas ningún número de tarjeta.",
"admCli": "Enviar correo también al cliente",
"admCliHelp": "En cuanto alguien reserva, recibe un recibo con los datos y el Pix para pagar. Después, cuando llegue el dinero, tocas \"Avisar al cliente\" en la reserva y recibe la confirmación.",
"admCliNota": "El recibo sale solo. La confirmación nunca sale sola — solo cuando la envías tú, porque solo tú sabes si el dinero entró.",
"admClients": "Clientes",
"admCoupons": "Cupones y regalos",
"admEntry": "Área de {guia}",
"admFx": "Mostrar el precio en reales a clientes brasileños",
"admFxHelp": "El tipo de cambio viene del Banco Central Europeo y se actualiza solo. El margen cubre el diferencial de conversión y la comisión del procesador — sin él, llegan menos euros que el precio pedido.",
"admFxMargem": "Margen sobre el cambio (%)",
"admHome": "Tu pantalla inicial",
"admHomeHelp": "Es lo que la persona ve al abrir la app. La foto va detrás de tu logotipo.",
"admHomePhoto": "Foto de fondo",
"admHomeText": "Frase de presentación",
"admIban": "IBAN",
"admIbanName": "Titular de la cuenta",
"admMoney": "Extracto",
"admPay": "Cómo cobras",
"admPayHelp": "Esto lo ve el cliente justo después de reservar. Deja en blanco lo que no uses — lo que esté vacío simplemente no aparece.",
"admPayNote": "Nota sobre el pago (opcional)",
"admPhoto": "Tu foto",
"admPhotoHelp": "Tú mirando a la cámara, en un lugar donde guías. Un buen selfie sirve.",
"admPixCity": "Ciudad de la cuenta",
"admPixHelp": "Nombre y ciudad son opcionales: quien paga ve el titular real que el banco obtiene de tu clave. Si los completas, escríbelos sin tildes.",
"admPixKey": "Clave Pix · es lo único que Pix necesita",
"admPixName": "Nombre en Pix",
"admPreview": "Ver como lo ve el cliente",
"admReports": "Informes",
"admSettings": "Ajustes",
"admTours": "Mis tours",
"adultsLbl": "Adultos",
"adultsSub": "18 años o más",
"agBooked": "{n} reservados",
"agDayOf": "Salidas del {d}",
"agFree": "{n} plazas",
"agLegend": "Los puntos muestran las salidas del día. Toca un día para ver quién viene.",
"agNext": "Mes siguiente",
"agNoDep": "Ninguna salida este día.",
"agPrev": "Mes anterior",
"agTitle": "Tu agenda",
"agToday": "Hoy",
"aproxBrl": "≈ {v} al cambio de hoy",
"askDatesBtn": "Preguntar fechas por WhatsApp",
"askPay": "Cobrar por WhatsApp",
"askPayMail": "Cobrar por correo",
"autoUpd": "Las actualizaciones son automáticas: cuando publico una mejora, la app se actualiza sola en tus dispositivos.",
"back": "Volver",
"backTours": "← Ver los tours",
"badEmail": "Revisa el correo — parece que falta algo.",
"balanceNote": "El saldo de {v} lo acordamos hasta el {d}.",
"balanceSoon": "El saldo de {v} lo acordamos antes del tour.",
"bigGroupBtn": "Pedir precio por WhatsApp",
"bkpClientes": "Descargar clientes y reservas (hoja de cálculo)",
"bkpFeito": "Copia descargada — guárdala en una carpeta tuya",
"bkpHelp": "Descarga todo a tu ordenador: clientes, reservas, pagos, tours y fechas. Guárdalo en una carpeta tuya. Hazlo una vez por semana en temporada.",
"bkpNunca": "Aún no has hecho ninguna copia de seguridad.",
"bkpTit": "Copia de seguridad de tus datos",
"bkpTudo": "Descargar todo (archivo de seguridad)",
"bkpUltimo": "Última copia: {d}",
"bkpVazio": "Aún no hay nada para descargar.",
"blockDays": "Bloquear días (vacaciones, compromisos)",
"bookAgain": "Hacer otra reserva",
"booked": "Está reservado.",
"cCode": "Código que escribe el cliente",
"cOnce": "1 vez por persona",
"cPct": "Descuento (%)",
"cUntil": "Válido hasta",
"cUses": "Usado {n} veces",
"cancelSm": "Cancelar",
"cancelled": "Cancelada",
"cardComo": "Irás a la página segura de Stripe. La tarjeta no pasa por aquí.",
"cardErro": "No pude abrir el pago. Prueba con Pix o escríbeme.",
"cardIndo": "Abriendo el pago…",
"cardPagar": "Pagar {v} con tarjeta",
"charged": "Recibido. {v} de {n}.",
"chargesTomorrow": "Cobro automático mañana",
"chooseTour": "Elige tu tour",
"clAll": "Todos",
"clCanMail": "{n} autorizaron contacto",
"clDlCsv": "Descargar lista (CSV)",
"clEmpty": "Aún no hay clientes. Se añaden solos cuando alguien reserva.",
"clNew": "Primera vez",
"clOnlyOptIn": "Solo quien autorizó",
"clRepeat": "Volvió {n}×",
"clTitle": "Tu base de clientes",
"clTotal": "{n} personas · {v} en total",
"closedPrice": "{n} personas · precio cerrado",
"confCliente": "Avisar al cliente",
"confClienteAsk": "¿Enviar la confirmación de pago a {email}?\n\nEl correo sale en un máximo de 30 minutos y no se puede deshacer.",
"confClienteFeito": "cliente avisado",
"confClienteOk": "Listo — {name} recibirá la confirmación",
"confirming": "Guardando tu lugar…",
"consentLbl": "Quiero recibir las novedades de {guia} por correo y WhatsApp",
"consentNo": "Solo reserva",
"consentWhy": "Nuevas fechas, promociones y las fotos de los tours. Sin esto, solo recibes lo relativo a tu reserva. Puedes darte de baja cuando quieras.",
"consentYes": "Acepta novedades",
"cont": "Continuar",
"contactHelp": "Es adonde llevan los botones de WhatsApp e Instagram de todo el sitio.",
"contactSaved": "Contacto guardado. Todos los botones del sitio ya apuntan a él.",
"copied": "Enlace copiado.",
"copiedOk": "Copiado",
"copyBtn": "Copiar",
"copyLink": "Copiar enlace",
"couponBad": "Ese cupón no existe o ya expiró. Revisa las letras.",
"couponOk": "Cupón {c} aplicado",
"create": "Crear",
"datesAutoSave": "Las fechas se guardan en cuanto las añades — no hace falta tocar Guardar aquí.",
"daysLate": "{n} días de retraso",
"delDo": "Borrar tour",
"delTour": "¿Borrar \"{n}\"?",
"delTourN": "Tiene {n} reservas futuras. No desaparecen, pero nadie más podrá reservarlo.",
"demoClear": "Borrar todo y empezar de cero",
"demoCleared": "Listo. App vacía — crea tu primer tour.",
"demoConfirm": "Esto borra TODOS los tours, reservas y clientes de ejemplo — en todos los dispositivos. No se puede deshacer. ¿Continuar?",
"demoOn": "Modo demostración",
"demoRestore": "Restaurar los ejemplos",
"demoRestored": "Ejemplos restaurados.",
"demoTit": "Estás en el panel — este es el lado de quien trabaja",
"demoTxt": "Prueba todo lo que quieras: crea un tour, cambia un precio, abre una reserva. Es una demostración, así que nada sale de este dispositivo y no se envía nada a nadie.",
"demoTxt2": "En tu app real esta área está protegida con tu contraseña, y solo entras tú.",
"demoWhat": "La app tiene tours y clientes de ejemplo para que pruebes todo funcionando. Cuando quieras empezar de verdad, solo tienes que borrarlos.",
"depositPaid": "Anticipo pagado · faltan {v}",
"dlCsv": "Descargar en Excel",
"dlQr": "Descargar el QR",
"draft": "Borrador — solo tú lo ves",
"dtAdicionar": "Añadir una fecha",
"dtBotao": "+ Añadir fecha",
"dtDia": "Día",
"dtEscolhaDia": "¿Qué días de la semana?",
"dtHora": "Horario",
"dtMarcadas": "Fechas ya programadas",
"dtNenhuma": "Aún no hay fechas. Añade la primera abajo.",
"dtPeriodo": "¿Durante qué período?",
"dtRepetir": "Repetir cada semana",
"dtRepetirOpc": "Opcional. Solo para tours que salen siempre los mismos días de la semana.",
"dtVagas": "Plazas",
"duplicate": "Duplicar",
"duplicated": "Copié \"{n}\". Cambia lo que necesites y publica.",
"earlyGone": "Las primeras plazas de esta fecha ya se agotaron",
"earlyLeft": "Aún quedan {n} plazas a este precio",
"earlyNote": "para las {n} primeras personas de esta fecha · después {v}",
"edAddStop": "Añadir parada",
"edBalanceDays": "Saldo hasta cuántos días antes",
"edBalanceWhy": "1 = el día anterior. 30 = un mes antes, como en los tours de Navidad.",
"edCancel": "Política de cancelación",
"edCancelWhy": "Aparece arriba de la página. Si el anticipo no es reembolsable, escríbelo aquí — por defecto se promete cancelación gratis.",
"edClosing": "Frase de cierre",
"edClosingWhy": "Lo último que la persona lee antes de decidir. Una frase tuya, no un eslogan.",
"edDistance": "Cuánto se camina",
"edDown": "Bajar",
"edDuration": "Cuánto dura",
"edEarly": "Quien reserva primero paga menos",
"edEarlySeats": "Cuántas plazas al precio más bajo",
"edEarlyWhy": "Déjalo en cero si el precio es único. Se cuenta por fecha: cada salida tiene sus propias primeras plazas.",
"edGroup": "Tamaño del grupo",
"edIncWhy": "Un elemento por línea. Así la pregunta \"¿el vin chaud está incluido?\" no se convierte en una reserva perdida.",
"edLatePrice": "Precio después de esas plazas",
"edMinWhy": "Por debajo de esto la salida no se realiza — el cliente ve este número.",
"edMoney": "Precio y reserva",
"edNoStops": "Aún no hay paradas. Añade la primera — con tres o cuatro la página ya cambia.",
"edPlace": "Dirección de la parada",
"edPriceNote": "Nota sobre el precio",
"edRemove": "Quitar",
"edRemoveAsk": "¿Quitar esta parada?",
"edRoute": "El recorrido del tour",
"edRouteWhy": "Es la parte de la página que más convence. Cada parada con horario, una foto y una frase tuya — como lo contarías en persona.",
"edStopName": "Nombre de la parada",
"edStopPhoto": "Foto del lugar. Una tuya vale más que una de internet.",
"edStopText": "Qué pasa allí",
"edTagline": "Frase de portada",
"edTaglineWhy": "La línea que aparece bajo el nombre. Es la que hace que la persona quiera leer el resto.",
"edTerms": "Condiciones",
"edTime": "Horario",
"edUp": "Subir",
"edit": "Editar",
"emAssina": "“{guia} · {negocio} · {base}”",
"emAviso": "🔒 “Este correo es el comprobante de tu reserva, no del pago.” — esta frase es fija. Sin ella, quien no pagó cree que todo está en orden.",
"emConfIntroPad": "Seu pagamento foi recebido e sua vaga está garantida. Nos vemos em breve!",
"emConfIntroPadEn": "Your payment has arrived and your place is secured. See you soon!",
"emConfQuando": "Solo sale con tu clic, porque solo tú sabes si llegó el dinero.",
"emConfTit": "2. Confirmación — cuando tocas \"Avisar al cliente\"",
"emDados": "— tour, fecha, personas, total, código, punto de encuentro —",
"emIntro": "Tu frase inicial",
"emOla": "“¡Hola, [nombre del cliente]!”",
"emPS": "Tu nota final",
"emPSex": "ej.: Lleva calzado cómodo y una chaqueta — allá arriba hace frío.",
"emPSexEn": "ej.: Bring comfortable shoes and a warm jacket.",
"emPix": "— cuánto pagar ahora y el código Pix, con el importe incluido —",
"emRecIntroPad": "Recebemos sua reserva. Abaixo está tudo o que você reservou e como pagar.",
"emRecIntroPadEn": "We have received your booking. Below is everything you booked and how to pay.",
"emRecQuando": "Sale solo, justo después de la reserva. Nunca dice que está pagado.",
"emRecTit": "1. Recibo — lo que recibe al reservar",
"emVazio": "Déjalo en blanco para usar el texto predeterminado. Lo que escribas aquí aparece en el correo exactamente así.",
"email": "Correo electrónico",
"emptyBookings": "Aún no hay reservas. En cuanto alguien reserve, aparecerá aquí.",
"emptyCoupons": "Ningún cupón activo. Un 10% de descuento para quien ya vino suele hacer que la gente vuelva.",
"emptyFilter": "No hay nada con este filtro. Ver todos los tours.",
"emptyTours": "Aún no tienes tours. Crea el primero y ya aparecerá en tu sitio — lleva unos 3 minutos.",
"enAuto": "Escribe solo en portugués. El inglés se traduce solo al guardar.",
"enFalhou": "No pude traducir ahora — se mantuvo el inglés anterior. ¿Guardar de todos modos?",
"enPronto": "Inglés traducido",
"enTraduzindo": "Traduciendo al inglés…",
"enVer": "Ver y ajustar el inglés",
"exBrasil": "Pix Brasil · fuera de la contabilidad francesa",
"exCsvCont": "CSV para el contable",
"exCsvTudo": "CSV completo",
"exNadaBr": "Ningún Pix en este período.",
"exTotalGeral": "Total recibido en el período",
"exit": "Salir",
"fAll": "Todos",
"fBike": "Bici",
"fDay": "Día completo",
"fDuration": "Duración",
"fGroup": "Grupo",
"fHours": "Horario",
"fLang": "Idiomas",
"fLeaves": "Salidas",
"fPhoto": "Foto",
"fWalk": "A pie",
"firstTour": "Crear mi primer tour",
"freeCancel": "Cancelación gratis hasta 48 h antes",
"fromLbl": "Desde",
"fromPrice": "desde",
"fullName": "Nombre completo",
"fxSemCotacao": "Sin tipo de cambio por ahora — el precio en reales no se muestra al cliente.",
"fxVelha": "cambio anterior, la red no respondió",
"goodMorning": "Buenos días, {guia}",
"gotBalance": "Recibí el saldo",
"haveCoupon": "¿Tienes un cupón?",
"homeSaved": "Pantalla inicial guardada",
"howGot": "Recibí por",
"howPay": "Cómo pagar",
"howPayNone": "Te paso los datos de pago por WhatsApp, junto con la confirmación.",
"howPayNow": "Para asegurar tu plaza",
"hubRedes": "Sígueme",
"hubRoteiro": "Arma tu experiencia",
"hubRoteiroSub": "Cuéntame lo que quieres y lo armo contigo",
"hubTransfer": "Traslado con chofer",
"hubTransferSub": "Aeropuerto y hotel — mira el precio al instante",
"hubViagem": "Para tu viaje",
"hubWhatsSub": "Respuesta directa conmigo",
"ibanLbl": "Transferencia (IBAN)",
"idadesFalta": "Elige la edad de cada niño para sumar las entradas.",
"inNameOf": "a nombre de",
"included": "Qué incluye",
"ingPagina": "Las entradas se suman en la reserva, según la edad de cada persona.",
"instaLbl": "Instagram · si quieres, te etiqueto en las fotos",
"installBtn": "Instalar en este dispositivo",
"installHelp": "Se convierte en un icono en tu pantalla, se abre a pantalla completa y funciona incluso sin internet.",
"installIos": "En iPhone: ábrelo en Safari → botón Compartir → “Añadir a pantalla de inicio”.",
"installTitle": "Instalar como aplicación",
"installed": "¡Instalado! Busca el icono verde en tu pantalla.",
"itinerary": "El recorrido, parada a parada",
"itineraryWhy": "Los horarios son aproximados — el tour va al ritmo del grupo, no del reloj.",
"keep": "Mantener",
"kidsLbl": "Niños",
"kidsSub": "menores de 18",
"kindBal": "Saldo",
"kindDep": "Anticipo",
"kindFull": "Completo",
"language": "Idioma del panel",
"lastSpotGone": "Alguien tomó la última plaza mientras completabas los datos. Elige otro horario.",
"lgErrConfirm": "Falta confirmar el correo. Busca el mensaje de confirmación en tu bandeja de entrada.",
"lgErrMuitas": "Demasiados intentos seguidos. Espera unos minutos e inténtalo de nuevo.",
"lgErrRede": "No pude conectar con el servidor. Revisa tu conexión a internet.",
"lgErrSenha": "El correo o la contraseña no coinciden. Revisa e inténtalo de nuevo.",
"lgEsqueci": "Si no recuerdas la contraseña, usa \"Olvidé mi contraseña\" aquí abajo.",
"linhaPreco": "{qtd} × {valor}",
"live": "Publicado",
"loginBack": "Ya tengo contraseña",
"loginBtn": "Entrar",
"loginConfirm": "¡Cuenta creada! Envié un correo de confirmación a {e}. Haz clic en el enlace y vuelve aquí para entrar.",
"loginCreate": "Crear mi cuenta",
"loginEmail": "Tu correo",
"loginFirst": "Es mi primer acceso — crear mi contraseña",
"loginForgot": "Olvidé mi contraseña",
"loginHi": "Qué bueno verte de nuevo, {guia}.",
"loginNoEmail": "Escribe tu correo.",
"loginOut": "Cerraste sesión. Tu área está bloqueada.",
"loginPass": "Tu contraseña",
"loginSafe": "Solo tú entras aquí. Tus clientes nunca ven esta pantalla.",
"loginSent": "Envié un enlace a {e}. Abre el correo y haz clic en él.",
"loginSub": "Inicia sesión para ver tus reservas y gestionar tus tours.",
"loginTaken": "Esta área ya pertenece a otra cuenta. Habla con Eugênio.",
"loginTitle": "Área de {guia}",
"loginWait": "Entrando…",
"loginWeak": "La contraseña necesita al menos 8 caracteres.",
"loginWrong": "El correo o la contraseña no coinciden.",
"mApple": "Apple Pay",
"mCard": "Tarjeta",
"mCash": "Efectivo",
"mOther": "Otro",
"mPix": "Pix",
"mTransfer": "Transferencia",
"mapOpen": "Ver el trayecto en el mapa",
"mapTitle": "El trayecto, en orden",
"mapWhyBike": "Se abre en tu app de mapas, con las {n} paradas marcadas y la ruta en bici.",
"mapWhyDrive": "Se abre en tu app de mapas, con las {n} paradas marcadas y la ruta en coche.",
"mapWhyWalk": "Se abre en tu app de mapas, con las {n} paradas marcadas y la ruta a pie.",
"maxNote": "Este tour admite hasta {n} personas. Para un grupo más grande, escríbeme por WhatsApp.",
"minAviso": "La salida se realiza a partir de {n} personas. Puedes reservar — te aviso si falta gente.",
"minNote": "Salida confirmada a partir de {n} personas.",
"msgGuia": "Hablar con {guia}",
"msgWhats": "Escribir por WhatsApp",
"myBooking": "Mi reserva",
"nParadas": "{n} paradas",
"newCoupon": "+ Nuevo cupón",
"newTour": "+ Nuevo tour",
"nlCta": "Iniciar sesión en mi cuenta",
"nlNotSaved": "⚠ No se guardó — primero inicia sesión en tu cuenta",
"nlTitle": "Tus reservas no aparecen aquí",
"nlWhy": "Los datos de tus clientes son privados: solo tú, con tu contraseña, puedes verlos. Mientras no inicies sesión, este panel solo muestra lo guardado en este dispositivo — y no las reservas que llegaron por el sitio.",
"nlWrite": "Y lo más importante: mientras no inicies sesión, nada de lo que edites aquí se guarda de verdad.",
"noDates": "Aún no hay fechas. Sin fecha, nadie puede reservar.",
"noDatesMonth": "No hay fechas este mes.",
"noDatesYet": "Este tour sale en fechas seleccionadas. Escríbeme y te paso las próximas — y te guardo el lugar.",
"noDepToday": "Hoy no tienes salidas. Buen descanso.",
"noHidden": "Sin cargos ocultos.",
"notIncluded": "No incluye",
"novaRes": "+ Añadir reserva",
"novaResSub": "Quien reservó por WhatsApp, Instagram o en persona se registra aquí — y pasa a contar en la agenda y en la caja.",
"novaResTit": "Reserva cerrada fuera de la app",
"npAgain": "Repite la contraseña",
"npFail": "No se pudo cambiar. Puede que el enlace haya expirado — pide otro.",
"npMismatch": "Las dos contraseñas no coinciden",
"npNew": "Nueva contraseña",
"npOk": "Contraseña cambiada. Qué bueno tenerte de vuelta.",
"npSave": "Guardar y entrar",
"npSub": "El enlace del correo funcionó. Ahora solo define una contraseña — al menos 8 caracteres.",
"npTitle": "Elige tu nueva contraseña",
"nrComo": "Cómo lo recibiste",
"nrData": "Fecha",
"nrEmail": "Correo (si tiene)",
"nrFaltaData": "Elige la fecha.",
"nrFaltaNome": "Escribe el nombre de la persona.",
"nrFeita": "Reserva añadida",
"nrHora": "Horario",
"nrNada": "Aún no he recibido nada",
"nrNome": "Nombre",
"nrPasseio": "Qué tour",
"nrPessoas": "Personas",
"nrSalvar": "Añadir reserva",
"nrSemVaga": "No cabe: solo quedan {n} plazas en esa salida.",
"nrValorAuto": "Calculado con el precio del tour. Cámbialo si acordaste otro importe.",
"nrWhats": "WhatsApp",
"oAgency": "Agencia",
"oFriend": "Recomendación",
"oInsta": "Instagram",
"oSite": "Sitio web",
"oWhats": "WhatsApp",
"oneOff": "Añadir una fecha suelta",
"openMap": "Ver el punto de encuentro en el mapa",
"orcForaCentro": "El hotel está fuera de la zona central (o hay más de una parada).",
"orcOi": "¡Hola, {guia}! Quería un presupuesto:",
"orcQuem": "{n} personas",
"orcQuemCri": "{a} adultos y {c} niños",
"origin": "Origen",
"paid": "Pagado",
"payAfter": "No se cobra nada ahora. En la siguiente pantalla verás cómo pagar.",
"payBtn": "Confirmar reserva · {v}",
"payFieldsSaved": "Datos de pago guardados",
"payFull": "Pagar todo de una vez",
"payFullSub": "Se resuelve en una sola transferencia.",
"payNowBtn": "Confirmar reserva · anticipo de {v}",
"payProof": "Después de pagar, envíame el comprobante por WhatsApp — te confirmo al momento.",
"paySplit": "Mitad ahora, mitad antes del tour",
"paySplitSub": "{half} para asegurar tu plaza. El saldo lo acordamos hasta {d} días antes del tour.",
"people": "personas",
"peopleLbl": "Personas",
"perGroup": "en total",
"perPerson": "por persona",
"perSession": "por sesión",
"perTrip": "por trayecto",
"pgConferindo": "Comprobando tu pago…",
"pgDuvida": "Si el importe salió de tu tarjeta, todo está bien — a veces el banco tarda unos minutos. Guarda el código <b>{code}</b> y, si quieres, habla con {guia}.",
"pgDuvidaTit": "Aún no pude confirmarlo",
"pgEspere": "Un momento, estoy consultando al banco.",
"pgOk": "Recibimos tu pago. Tu reserva <b>{code}</b> está asegurada — {guia} ya recibió el aviso.",
"pgOkTit": "Pago confirmado",
"pickDate": "Elige una fecha",
"pickTime": "Ahora elige el horario",
"pixComo": "En el ordenador, apunta la cámara del teléfono al código de arriba. En el teléfono, cópialo y pégalo en tu banco en \"Pix Copia e Cola\". El importe ya va incluido — no escribes nada.",
"pixCopiado": "Código copiado",
"pixCopiar": "Copiar código Pix",
"pixDepois": "Después de pagar, envíame el comprobante por WhatsApp — te confirmo al momento.",
"pixLbl": "Pix (clave)",
"pixTit": "Pagar con Pix",
"pixValor": "{brl} · equivale a {eur} al cambio de hoy",
"placeholderWarn": "Este número es de ejemplo — cámbialo por tu WhatsApp real.",
"priceSplit": "{a} × {va} + {b} × {vb}",
"print": "Imprimir / PDF",
"protectLater": "Ahora no",
"protectNow": "Crear mi contraseña ahora",
"protectTitle": "Protege tu área con una contraseña",
"protectWhy": "Ahora mismo cualquiera con el enlace llega a tu panel. Crea tu cuenta y solo entrarás tú.",
"published": "Publicado. Ya se puede reservar.",
"qrHelp": "Imprímelo o muéstralo en pantalla — la persona apunta la cámara y llega directo a tus tours.",
"qrTitle": "Código QR",
"received": "Recibido en el período",
"repeats": "Se repite cada semana",
"repeatsEg": "Ej.: cada martes, jueves y sábado a las 16:30",
"resetDemo": "Reiniciar con datos de ejemplo",
"resetWarn": "Esto borra todo lo que creaste y vuelve al ejemplo. ¿Continuar?",
"ressyncBtn": "Traer todo del servidor",
"ressyncHelp": "Borra lo guardado en este dispositivo y vuelve a traer todo del servidor. Tus tours y reservas no se pierden — están en el servidor, no aquí.",
"ressyncPerg": "¿Volver a traer todo del servidor? No se borra nada en el servidor.",
"ressyncTit": "¿La app muestra algo mal?",
"reviews": "Lo que dicen quienes ya vinieron",
"role": "{negocio} · {base}",
"rpByMonth": "Recibido mes a mes",
"rpByTour": "Rendimiento por tour",
"rpByWeek": "Recibido en las últimas 8 semanas",
"rpDeps": "Salidas",
"rpDue": "Pendiente de cobro",
"rpEmpty": "Sin movimiento en este período.",
"rpOrigin": "De dónde vinieron las reservas",
"rpOriginHelp": "Muestra dónde vale la pena invertir tu tiempo.",
"rpPax": "Personas",
"rpRevenue": "Recibido",
"rpTicket": "Media por persona",
"rpTitle": "Cómo fue el período",
"rtChega": "Llegada",
"rtConte": "Cuéntame más",
"rtContePh": "Una fecha especial, un lugar soñado, alguien con dificultad para caminar…",
"rtEnviar": "Enviar a {guia} por WhatsApp",
"rtFalta": "Completa tu nombre y WhatsApp.",
"rtFine": "No es una reserva y no hay compromiso: es el comienzo de la conversación.",
"rtGosto": "Qué les gusta",
"rtIdades": "Edad de los niños",
"rtIdadesPh": "ej.: 4 y 9 años",
"rtIntro": "Cuéntame cómo es tu viaje y qué te gusta. Recibo todo en WhatsApp y armo una propuesta a la medida para ustedes.",
"rtOk": "¡Pedido enviado!",
"rtOkSub": "WhatsApp se abrió con todo listo: solo toca enviar. {guia} responde con la propuesta.",
"rtOnde": "Adónde quieres ir",
"rtOndeOutro": "¿Otro lugar?",
"rtPrecisa": "Necesitas ayuda con",
"rtQuando": "Cuándo",
"rtQuem": "Quién viene",
"rtReenviar": "Abrir WhatsApp de nuevo",
"rtRitmo": "Ritmo del viaje",
"rtSai": "Salida",
"rtVarios": "Puedes marcar más de uno.",
"rtVoce": "Tus datos",
"saveBtn": "Guardar",
"saveContact": "Guardar mi contacto",
"saveDraft": "Guardar como borrador",
"savePub": "Guardar y publicar",
"sbNew": "Tour nuevo",
"sbTour": "Este tour",
"seasonal": "De temporada",
"seats": "Plazas en esta salida",
"secDates": "Fechas y horarios",
"secIncludes": "Qué incluye",
"secPrice": "Precio y reserva",
"secProgram": "El programa",
"secStops": "El recorrido, parada por parada",
"secStopsSub": "{n} paradas · {d} con {guia}",
"seeMap": "Ver en el mapa",
"seeTours": "Ver tours y reservar",
"seeToursSub": "Fechas libres y reserva al instante",
"sendMsg": "Escribir por WhatsApp",
"sentAll": "Guarda el código de abajo. Toca el botón verde para avisarme por WhatsApp — así ya te confirmo todo.",
"share": "Compartir",
"shareLink": "El enlace para tus clientes",
"sndBlocked": "El navegador solo permite sonido tras un toque en la pantalla. Toca en cualquier lugar y vuelve a escuchar.",
"sndOff": "Sin sonido",
"sndOn": "Con sonido",
"sndTest": "Escuchar",
"sndTitle": "Apertura de la app",
"sndWhy": "La marca se dibuja con tres campanas y el clic del obturador — guía y fotógrafa. Aparece una vez por visita y un toque la salta.",
"soldOut": "Agotado este mes",
"spotsLeft": "plazas",
"stAte": "hasta {d}",
"stAtrasado": "{n} días de retraso",
"stDeTotal": "{pago} de {total}",
"stEmpty": "Nada recibido en este período.",
"stEsperando": "Nada recibido",
"stFalta": "faltan {v}",
"stPago": "Pagado",
"stSinal": "Anticipo recibido",
"stTitle": "Extracto de cobros",
"step1": "1 de 4 · Elige la fecha",
"step2": "2 de 4 · Cuántas personas",
"step3": "3 de 4 · Tus datos y pago",
"step4": "¡Listo!",
"stopsCount": "paradas",
"syncNote": "Por ahora, cada dispositivo guarda sus propios datos. La sincronización entre el teléfono y el portátil llega con la base de datos en la nube (próxima etapa).",
"tBike": "Bici",
"tDesc": "Cuenta lo que la persona va a vivir (PT)",
"tDescEn": "En inglés",
"tDescHelp": "Escribe como hablas.",
"tMax": "Llevo como máximo",
"tMeeting": "Punto de encuentro",
"tMin": "No salgo con menos de",
"tName": "¿Cómo se llama este tour? (PT)",
"tNameEn": "Y en inglés",
"tPay": "Cómo quieres cobrar",
"tPayFull": "Todo al reservar",
"tPaySplit": "Mitad al reservar, mitad el día antes",
"tPhoto": "Foto del tour",
"tPhotoBad": "No pude leer esa imagen. Prueba con un JPG o PNG.",
"tPhotoHelp": "Elige una foto tuya. Es la que aparece en la tarjeta y arriba de la página del tour.",
"tPhotoOk": "Foto cambiada. Guarda para publicar.",
"tPhotoT": "Tour fotográfico",
"tPriceMode": "Se cobra",
"tRegion": "¿Dónde se realiza?",
"tSession": "Sesión de fotos",
"tType": "¿De qué tipo es?",
"tWalk": "A pie",
"tagline": "Visitas guiadas en portugués. Grupos pequeños, a tu ritmo.",
"temaAuto": "Automático",
"temaAutoSub": "Sigue el dispositivo de cada uno",
"temaClaro": "Claro",
"temaClaroSub": "Siempre claro",
"temaEscuro": "Oscuro",
"temaEscuroSub": "Siempre oscuro",
"temaHelp": "Se aplica a ti y a quien abra la app. En automático, cada persona lo ve según su propio dispositivo.",
"temaSalvo": "Apariencia guardada",
"temaTit": "Apariencia",
"thisMonth": "Este mes",
"thisWeek": "Esta semana",
"timeLbl": "Horario",
"total": "Total",
"trfDay": "Día",
"trfNight": "Noche",
"trfNightOn": "Horario nocturno",
"trfSinalLbl": "Seña para asegurar",
"trfSinalNota": "Ahora pagas solo la seña, {s}. El resto, {r}, se paga el día del traslado.",
"tutDone": "¡Listo! Si tienes dudas, el tutorial vuelve desde Ajustes.",
"tutNext": "Entendido",
"tutSkip": "Saltar tutorial",
"tutorial": "Tutorial",
"tutorialOn": "Ver el tutorial de nuevo",
"unpublished": "Sin publicar. Nadie puede reservar.",
"untilLbl": "Hasta",
"upTo": "hasta",
"vDesc": "Escribe lo que la persona va a vivir.",
"vFix": "Falta completar {n} campo(s) — los marqué en rojo.",
"vMeet": "Indica el punto de encuentro.",
"vMinMax": "El mínimo no puede ser mayor que el máximo.",
"vName": "Ponle un nombre al tour.",
"vPrice": "El precio tiene que ser mayor que cero.",
"viewSite": "Ver mi sitio",
"waAskDates": "¡Hola, {guia}! Vi el tour {tour} en tu app y quería saber las próximas fechas 🙂",
"waBookingMsg": "¡Hola, {guia}! Acabo de reservar: {tour}, {when}. Mi código es {code}. Soy {name} 🙂",
"waCharge": "¡Hola, {name}! Soy {guia} 🙂 Faltan {v} del tour {tour} ({when}). ¿Puedes pagarlo por aquí? ¡Gracias!",
"waHello": "¡Hola, {guia}! Vi tu app de tours y quiero saber más 🙂",
"waHi": "¡Hola, {name}! Soy {guia} 🙂 Sobre tu tour {tour}, {when} — ¿todo bien por ahí?",
"waSendBooking": "Presentarme en el WhatsApp de {guia}",
"waitingPay": "Esperando pago · {v}",
"whatsLbl": "WhatsApp (con prefijo del país)",
"whatsapp": "Escríbeme por WhatsApp",
"whenRuns": "Cuándo se realiza este tour",
"whereWeMeet": "Dónde nos encontramos",
"whyWhats": "Por aquí te envío el punto de encuentro y te aviso si cambia algo.",
"yourCode": "Tu código",
"yourContact": "Tu contacto",
"yourInsta": "Tu Instagram (sin @)",
"yourWhats": "Tu WhatsApp (con prefijo del país)"
};

/* o que era da EmRoma e na Yalla tem outro texto */
const STR_YALLA = {
 "seeTours": { "pt": "Ver experiências", "en": "See the experiences", "es": "Ver experiencias" },
 "seeToursSub": { "pt": "Privativas, corporativas e sob medida", "en": "Private, corporate and bespoke", "es": "Privadas, corporativas y a medida" },
 "hubRoteiro": {
  "pt": "Monte a sua experiência",
  "en": "Build your experience"
 },
 "hubTransferSub": {
  "pt": "Aeroporto e hotel — veja o valor na hora",
  "en": "Airport and hotel — see the price right away"
 },
 "orcForaCentro": {
  "pt": "O hotel é fora da área central (ou tem mais de uma parada).",
  "en": "The hotel is outside the central area (or there is more than one stop)."
 }
};

/* achadas na revisão do navegador (01/10/2026) */
Object.assign(STR_ES, { hubAval: 'Reseñas', hubAvalSub: 'Lo que dicen los clientes', tutTitulo: 'Consejo de la app', tutOuvir: 'Escuchar' });

for (const k in STR_YALLA) if (STR[k]) Object.assign(STR[k], STR_YALLA[k]);
for (const k in STR_ES) if (STR[k] && !(STR_YALLA[k] && STR_YALLA[k].es)) STR[k].es = STR_ES[k];

/* o app.js já desenhou a primeira tela antes deste arquivo carregar:
   quem abriu em espanhol vê a tela de novo, já traduzida */
if (typeof LANG !== 'undefined' && LANG === 'es' && typeof route === 'function') route();
