/* =====================================================
   BANCO DE PONTOS TURÍSTICOS — demo "Londres com a Bia" (07/10/2026)

   Os lugares são sempre os mesmos; o que muda é como cada guia os combina.
   Este banco alimenta os tours, e o "Monte seu roteiro".
   Textos: escritos para esta demonstração, a partir de fatos públicos sobre
   cada lugar (fonte "demo"). O guia troca pelo texto dele no painel.
   Fotos: Wikimedia Commons, com autor e licença (cr).
   ===================================================== */
'use strict';

const PONTOS = [
  {"id":"parlamento","n":"Parlamento (Palácio de Westminster)","area":"westminster","lat":51.499167,"lng":-0.124722,"d":"O Palácio de Westminster é a sede do Parlamento britânico desde a Idade Média. O prédio atual, em estilo neogótico, foi erguido depois do incêndio de 1834 e tem mais de mil salas.","dica":"A fachada mais bonita é vista do outro lado do rio, da ponte de Westminster.","ph":"fotos/p-parlamento.jpg","cr":"Foto: ThatsTheBoss · CC0 · Wikimedia Commons","fonte":"demo"},
  {"id":"big-ben","n":"Big Ben","area":"westminster","lat":51.5007,"lng":-0.1245,"d":"Big Ben é o apelido do sino de 13 toneladas dentro da Elizabeth Tower, não da torre em si. O relógio funciona desde 1859 e passou por uma grande restauração entre 2017 e 2022.","dica":"Para ouvir as badaladas inteiras, chegue uns minutos antes da hora cheia.","ph":"fotos/p-big-ben.jpg","cr":"Foto: Christian David · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"abadia","n":"Abadia de Westminster","area":"westminster","lat":51.499444,"lng":-0.1275,"d":"A Abadia de Westminster é o palco das coroações britânicas desde 1066 e guarda os túmulos de reis, cientistas e poetas, de Isaac Newton a Charles Dickens. Também foi onde aconteceram casamentos reais recentes.","dica":"Fecha para turistas aos domingos. Para entrar, compre o ingresso com antecedência no site oficial.","ph":"fotos/p-abadia.jpg","cr":"Foto: Antiquary · CC BY 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"buckingham","n":"Palácio de Buckingham","area":"westminster","lat":51.500833,"lng":-0.141944,"d":"O Palácio de Buckingham é a residência oficial do monarca em Londres desde 1837 e tem 775 cômodos. Quando a bandeira real está hasteada, o rei está em casa.","dica":"As salas de Estado abrem ao público só no verão, geralmente de julho a setembro.","ph":"fotos/p-buckingham.jpg","cr":"Foto: Julian Herzog (Website) · CC BY 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"troca-guarda","n":"Troca da Guarda","area":"westminster","lat":51.501,"lng":-0.1416,"d":"A Troca da Guarda é a cerimônia em que os soldados que protegem o palácio passam o posto, com banda e uniformes de gala. Dura cerca de 45 minutos e acontece em dias fixos da semana.","dica":"Chegue com 45 minutos de antecedência para pegar lugar na grade, ou assista com menos gente na Horse Guards.","ph":"fotos/p-troca-guarda.jpg","cr":"Foto: MaryG90 · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"horse-guards","n":"Horse Guards Parade","area":"westminster","lat":51.5047,"lng":-0.1283,"d":"A Horse Guards Parade é a antiga área de torneios do palácio de Whitehall e hoje é o cenário do Trooping the Colour, o desfile de aniversário do monarca. Os guardas a cavalo ficam de sentinela na entrada.","dica":"A troca da guarda montada é às 11h (10h aos domingos) e costuma ter bem menos gente que a de Buckingham.","ph":"fotos/p-horse-guards.jpg","cr":"Foto: Central Office of Information official photographer · domínio público · Wikimedia Commons","fonte":"demo"},
  {"id":"downing","n":"10 Downing Street","area":"westminster","lat":51.5033,"lng":-0.1275,"d":"No número 10 da Downing Street mora e trabalha o primeiro-ministro britânico desde 1735. A rua é fechada por grades, mas dá para ver a porta preta famosa pelo portão.","dica":"Fique do lado da Whitehall e use o zoom: a foto da porta sai bem de lá.","ph":"fotos/p-downing.jpg","cr":"Foto: Sergeant Tom Robinson RLC · OGL v1.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"churchill","n":"Churchill War Rooms","area":"westminster","lat":51.502083,"lng":-0.129028,"d":"As Churchill War Rooms são o bunker subterrâneo de onde o governo britânico comandou a Segunda Guerra Mundial. As salas ficaram como estavam em 1945, com mapas, telefones e camas.","dica":"É pequeno e lota: compre com horário marcado.","ph":"fotos/p-churchill.jpg","cr":"Foto: Kaihsu Tai derivative work: SilkTork (talk) · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"trafalgar","n":"Trafalgar Square","area":"westminster","lat":51.508056,"lng":-0.128056,"d":"A Trafalgar Square celebra a vitória naval de 1805 contra Napoleão. No centro, a coluna do almirante Nelson tem 52 metros; os quatro leões de bronze foram fundidos com canhões franceses derrotados.","dica":"A National Gallery fica bem ali, com entrada gratuita.","ph":"fotos/p-trafalgar.jpg","cr":"Foto: Diliff · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"national-gallery","n":"National Gallery","area":"westminster","lat":51.5089,"lng":-0.1283,"d":"A National Gallery reúne mais de 2.300 pinturas europeias do século XIII ao início do XX, de Van Gogh a Leonardo da Vinci, com entrada gratuita desde a fundação em 1824.","dica":"Vá direto às salas dos impressionistas se tiver pouco tempo.","ph":"fotos/p-national-gallery.jpg","cr":"Foto: Diego Delso · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"st-james-park","n":"St James's Park","area":"westminster","lat":51.5025,"lng":-0.135,"d":"O St James's Park é o parque real mais antigo de Londres e fica entre o Palácio de Buckingham e a Horse Guards. O lago tem pelicanos desde 1664, presente de um embaixador russo.","dica":"Da ponte azul do lago sai a foto mais bonita de Buckingham, com as árvores em volta.","ph":"fotos/p-st-james-park.jpg","cr":"Foto: Colin · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"london-eye","n":"London Eye","area":"southbank","lat":51.5033,"lng":-0.1194,"d":"O London Eye é a roda-gigante de 135 metros na margem sul do Tâmisa, inaugurada para a virada do ano 2000. Uma volta completa leva 30 minutos e, em dia limpo, dá para ver 40 km ao redor.","dica":"O pôr do sol é o horário mais bonito e também o mais disputado: compre antes.","ph":"fotos/p-london-eye.jpg","cr":"Foto: Khamtran · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"st-pauls","n":"Catedral de St. Paul","area":"city","lat":51.513739,"lng":-0.098393,"d":"A Catedral de St Paul's foi desenhada por Christopher Wren depois do Grande Incêndio de 1666 e tem uma das maiores cúpulas do mundo. Foi aqui que Charles e Diana se casaram, em 1981.","dica":"São 528 degraus até o topo da cúpula, mas a vista compensa.","ph":"fotos/p-st-pauls.jpg","cr":"Foto: Mark Fosh · CC BY 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"millennium-bridge","n":"Millennium Bridge","area":"city","lat":51.510157,"lng":-0.098467,"d":"A Millennium Bridge é uma ponte só para pedestres, inaugurada em 2000, ligando a St Paul's à Tate Modern. Ela aparece no filme Harry Potter e o Enigma do Príncipe.","dica":"Do meio da ponte sai a melhor foto da cúpula da catedral.","ph":"fotos/p-millennium-bridge.jpg","cr":"Foto: Ibex73 · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"bank-of-england","n":"Bank of England","area":"city","lat":51.513675,"lng":-0.088819,"d":"O Banco da Inglaterra foi fundado em 1694 e é o banco central do Reino Unido, responsável pelas notas de libra. Em seus cofres fica uma das maiores reservas de ouro do mundo.","dica":"O museu do banco é gratuito e deixa você levantar uma barra de ouro de verdade.","ph":"fotos/p-bank-of-england.jpg","cr":"Foto: acediscovery · CC BY 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"royal-exchange","n":"Royal Exchange","area":"city","lat":51.513541,"lng":-0.088194,"d":"O Royal Exchange foi a primeira bolsa de valores de Londres, fundada em 1566. O prédio atual, de 1844, hoje abriga lojas de luxo e um café no pátio central.","dica":"Entre para ver o pátio coberto: é bonito e não custa nada.","ph":"fotos/p-royal-exchange.jpg","cr":"Foto: Diego Delso · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"leadenhall","n":"Leadenhall Market","area":"city","lat":51.5129,"lng":-0.084864,"d":"O Leadenhall Market é um mercado coberto vitoriano de 1881, com teto de ferro e vidro pintado em vinho e dourado. Serviu de cenário para o Beco Diagonal no primeiro filme de Harry Potter.","dica":"Vá na hora do almoço de um dia útil para ver a City em movimento.","ph":"fotos/p-leadenhall.jpg","cr":"Foto: Diliff · CC BY 2.5 · Wikimedia Commons","fonte":"demo"},
  {"id":"sky-garden","n":"Sky Garden","area":"city","lat":51.511231,"lng":-0.083727,"d":"O Sky Garden é um jardim público no topo do edifício 20 Fenchurch Street, apelidado de Walkie-Talkie. A visita é gratuita e tem vista para toda a cidade.","dica":"Grátis, mas precisa reservar online com alguns dias de antecedência.","ph":"fotos/p-sky-garden.jpg","cr":"Foto: Colin · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"horizon-22","n":"Horizon 22 (22 Bishopsgate)","area":"city","lat":51.514419,"lng":-0.083048,"d":"O Horizon 22 é o mirante gratuito mais alto da Europa, no 58º andar do edifício 22 Bishopsgate. Abriu em 2023 e tem vista para o Shard, a Torre e o rio.","dica":"Reserve pelo site oficial; o horário do fim da tarde esgota primeiro.","ph":"fotos/p-horizon-22.jpg","cr":"Foto: M R Karim Reza · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"monument","n":"Monumento ao Grande Incêndio","area":"city","lat":51.51037,"lng":-0.085878,"d":"O Monumento ao Grande Incêndio é uma coluna de 61 metros desenhada por Christopher Wren, erguida perto da padaria onde o fogo de 1666 começou. Se a coluna caísse na direção certa, tocaria o ponto exato.","dica":"São 311 degraus até o topo, por uma escada em espiral.","ph":"fotos/p-monument.jpg","cr":"Foto: Eluveitie · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"tower-of-london","n":"Torre de Londres","area":"city","lat":51.507692,"lng":-0.076781,"d":"A Torre de Londres é uma fortaleza fundada por Guilherme, o Conquistador, em 1078. Já foi palácio, prisão e casa da moeda, e hoje guarda as Joias da Coroa.","dica":"Entre cedo e vá direto às Joias da Coroa, antes da fila crescer.","ph":"fotos/p-tower-of-london.jpg","cr":"Foto: [Duncan] from Nottingham, UK · CC BY 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"joias-coroa","n":"Joias da Coroa","area":"city","lat":51.5081,"lng":-0.0759,"d":"As Joias da Coroa ficam na Torre de Londres e incluem as coroas, cetros e espadas usados nas coroações britânicas, com mais de 23 mil pedras preciosas.","dica":"A esteira rolante em frente às coroas é propositalmente lenta; passe duas vezes se quiser.","ph":"fotos/p-joias-coroa.jpg","cr":"Foto: United Kingdom Government · domínio público · Wikimedia Commons","fonte":"demo"},
  {"id":"tower-bridge","n":"Tower Bridge","area":"city","lat":51.505737,"lng":-0.075721,"d":"A Tower Bridge foi inaugurada em 1894 e é a ponte mais famosa de Londres, com duas torres e um vão que abre para navios. Muita gente a confunde com a London Bridge, que é bem simples.","dica":"O horário em que a ponte abre está no site oficial; vale programar a visita.","ph":"fotos/p-tower-bridge.jpg","cr":"Foto: Fuzzypiggy · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"gherkin","n":"The Gherkin (30 St Mary Axe)","area":"city","lat":51.51433,"lng":-0.080033,"d":"O Gherkin, oficialmente 30 St Mary Axe, é o arranha-céu em forma de pepino desenhado por Norman Foster e concluído em 2003. Virou um dos símbolos da City moderna.","dica":"A melhor foto é da esquina da St Helen's Church, com a igreja medieval na frente.","ph":"fotos/p-gherkin.jpg","cr":"Foto: Paste at English Wikipedia · domínio público · Wikimedia Commons","fonte":"demo"},
  {"id":"tate-modern","n":"Tate Modern","area":"southbank","lat":51.507595,"lng":-0.099356,"d":"A Tate Modern é o museu de arte moderna e contemporânea de Londres, instalado numa antiga usina elétrica à beira do Tâmisa. A entrada para a coleção permanente é gratuita.","dica":"Suba ao terraço do prédio novo: a vista da St Paul's é de graça.","ph":"fotos/p-tate-modern.jpg","cr":"Foto: Acabashi · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"globe","n":"Shakespeare's Globe","area":"southbank","lat":51.508076,"lng":-0.097194,"d":"O Shakespeare's Globe é uma reconstrução fiel do teatro elisabetano de 1599 onde as peças de Shakespeare foram encenadas. As apresentações acontecem ao ar livre, como na época.","dica":"Ingressos em pé no pátio custam pouco e são a experiência mais autêntica.","ph":"fotos/p-globe.jpg","cr":"Foto: Diego Delso · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"borough-market","n":"Borough Market","area":"southbank","lat":51.505542,"lng":-0.090803,"d":"O Borough Market é o mercado de comida mais antigo de Londres, com mais de mil anos de história no mesmo bairro. Hoje reúne queijos, pães, frutos do mar e comida de rua do mundo todo.","dica":"Vá com fome e evite o sábado ao meio-dia, quando fica difícil andar.","ph":"fotos/p-borough-market.jpg","cr":"Foto: Øyvind Holmstad · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"southwark-cathedral","n":"Catedral de Southwark","area":"southbank","lat":51.506101,"lng":-0.089596,"d":"A Catedral de Southwark é a igreja gótica mais antiga de Londres, com partes do século XIII, e fica colada ao Borough Market. Shakespeare frequentava a paróquia.","dica":"Entrada gratuita; o jardim lateral é um bom lugar para comer o que você comprou no mercado.","ph":"fotos/p-southwark-cathedral.jpg","cr":"Foto: Ethan Doyle White · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"shard","n":"The Shard","area":"southbank","lat":51.5045,"lng":-0.0865,"d":"O Shard é o prédio mais alto do Reino Unido, com 310 metros, desenhado por Renzo Piano e inaugurado em 2012. O mirante fica nos andares 68 a 72.","dica":"O mirante é pago; se quiser vista de graça, prefira o Sky Garden ou o Horizon 22.","ph":"fotos/p-shard.jpg","cr":"Foto: Colin · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"british-museum","n":"Museu Britânico","area":"bloomsbury","lat":51.5194,"lng":-0.1269,"d":"O Museu Britânico foi fundado em 1753 e é o museu público mais antigo do mundo, com cerca de 8 milhões de objetos de todos os continentes. A entrada é gratuita.","dica":"Chegue na abertura, às 10h, para passar rápido pela revista de bolsas.","ph":"fotos/p-british-museum.jpg","cr":"Foto: Ham · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"great-court","n":"Great Court do Museu Britânico","area":"bloomsbury","lat":51.519444,"lng":-0.126944,"d":"O Great Court é o pátio central do Museu Britânico, coberto em 2000 por um teto de vidro com 3.312 painéis, todos diferentes. No meio fica a antiga Sala de Leitura circular.","dica":"É o melhor ponto de encontro do museu, bem debaixo do teto.","ph":"fotos/p-great-court.jpg","cr":"Foto: Diliff · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"rosetta","n":"Pedra de Roseta","area":"bloomsbury","lat":51.5194,"lng":-0.127,"d":"A Pedra de Roseta tem o mesmo decreto escrito em três alfabetos e foi a chave para decifrar os hieróglifos egípcios, em 1822. Está no museu desde 1802.","dica":"Fica na sala 4, logo à esquerda da entrada principal; vá antes dos grupos chegarem.","ph":"fotos/p-rosetta.jpg","cr":"Foto: Hans Hillewaert · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"egito-bm","n":"Galeria Egípcia do Museu Britânico","area":"bloomsbury","lat":51.5194,"lng":-0.127,"d":"As galerias egípcias do Museu Britânico guardam múmias, sarcófagos e papiros com mais de três mil anos. É a maior coleção fora do Egito.","dica":"As múmias ficam no andar de cima, salas 62 e 63.","ph":"fotos/p-egito-bm.jpg","cr":"Foto: Gary Todd from Xinzheng, China · CC0 · Wikimedia Commons","fonte":"demo"},
  {"id":"parthenon","n":"Mármores do Partenon","area":"bloomsbury","lat":51.5192,"lng":-0.1283,"d":"As esculturas do Partenon são os frisos e estátuas de mármore do templo de Atena, em Atenas, trazidos a Londres no início do século XIX. A Grécia pede a devolução há décadas.","dica":"Sente nos bancos da sala 18 e observe os cavalos do friso: cada um tem uma expressão.","ph":"fotos/p-parthenon.jpg","cr":"Foto: Jay.M · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"assirios","n":"Relevos assírios","area":"bloomsbury","lat":51.5194,"lng":-0.127,"d":"Os relevos assírios mostram caçadas de leões e cenas de palácio esculpidas há quase 2.700 anos em Nínive e Nimrud, no atual Iraque. Os detalhes dos animais impressionam até hoje.","dica":"Os portões com touros alados ficam logo depois da Pedra de Roseta.","ph":"fotos/p-assirios.jpg","cr":"Foto: Carole Raddato from FRANKFURT, Germany · CC BY-SA 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"selfridges","n":"Selfridges","area":"mayfair","lat":51.514178,"lng":-0.152628,"d":"A Selfridges é a loja de departamentos que inventou o conceito de \"fazer compras por prazer\", em 1909. Suas vitrines de Natal são famosas.","dica":"O andar de comida e a área de perfumes valem a visita mesmo sem comprar.","ph":"fotos/p-selfridges.jpg","cr":"Foto: Steve Daniels · CC BY-SA 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"bond-street","n":"New Bond Street","area":"mayfair","lat":51.5126,"lng":-0.1448,"d":"A Bond Street é a rua das grifes de luxo e das casas de leilão, como a Sotheby's. É vizinha das galerias de arte de Mayfair.","dica":"A estátua de Churchill e Roosevelt sentados num banco é a foto da rua.","ph":"fotos/p-bond-street.jpg","cr":"Foto: autor no Wikimedia Commons · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"burlington","n":"Burlington Arcade","area":"mayfair","lat":51.509,"lng":-0.1403,"d":"A Burlington Arcade é uma galeria coberta de 1819, com guardas de cartola, os \"beadles\", que ainda proíbem correr e assobiar.","dica":"Pergunte a um beadle sobre as regras da galeria: eles adoram contar.","ph":"fotos/p-burlington.jpg","cr":"Foto: autor no Wikimedia Commons · CC BY-SA 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"fortnum","n":"Fortnum & Mason","area":"mayfair","lat":51.5083,"lng":-0.1384,"d":"A Fortnum & Mason é a mercearia de luxo de 1707 que inventou o ovo cozido com casca de pastel e abastece a realeza. Famosa pelos chás e pelas cestas de piquenique.","dica":"O relógio da fachada toca de hora em hora com bonecos dos fundadores.","ph":"fotos/p-fortnum.jpg","cr":"Foto: Tony Hisgett from Birmingham, UK · CC BY 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"notting-hill","n":"Portobello Road (Notting Hill)","area":"kensington","lat":51.51618,"lng":-0.20517,"d":"Notting Hill é o bairro das casas coloridas e da Portobello Road, o mercado de antiguidades que ganhou o mundo com o filme de 1999. No fim de agosto, o Carnaval de Notting Hill leva um milhão de pessoas às ruas.","dica":"A feira de Portobello é maior aos sábados; para fotos com calma, vá de manhã num dia de semana.","ph":"fotos/p-notting-hill.jpg","cr":"Foto: Schellack at English Wikipedia · CC BY 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"kensington-palace","n":"Palácio de Kensington","area":"kensington","lat":51.505278,"lng":-0.188333,"d":"O Palácio de Kensington foi a casa da Princesa Diana e é onde a Rainha Vitória nasceu. Parte dele é aberta ao público, com exposições de roupas da realeza.","dica":"O jardim submerso em frente é gratuito e floresce de abril a setembro.","ph":"fotos/p-kensington-palace.jpg","cr":"Foto: Colin Smith · CC BY-SA 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"hyde-park","n":"Hyde Park","area":"kensington","lat":51.508611,"lng":-0.163611,"d":"O Hyde Park é o maior parque real do centro de Londres, com 142 hectares, o lago Serpentine e o Speakers' Corner, onde qualquer pessoa pode discursar.","dica":"Alugue um barquinho no Serpentine ou só sente na grama; o parque é feito para isso.","ph":"fotos/p-hyde-park.jpg","cr":"Foto: @LondonNPC #NationalParkCity · CC BY 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"nhm","n":"Museu de História Natural","area":"kensington","lat":51.496111,"lng":-0.176389,"d":"O Museu de História Natural é famoso pelo esqueleto de baleia azul no hall e pelos dinossauros, num prédio de 1881 que parece uma catedral. Entrada gratuita.","dica":"Com criança, vá direto à galeria dos dinossauros e depois à baleia.","ph":"fotos/p-nhm.jpg","cr":"Foto: Daniel Lu (User:dllu) · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"harrods","n":"Harrods","area":"kensington","lat":51.499722,"lng":-0.163611,"d":"A Harrods é a loja de departamentos mais famosa de Londres, com 330 setores em sete andares, e já teve a fama de vender qualquer coisa, até elefante.","dica":"O hall de comida egípcio e a escada rolante egípcia são as partes mais fotografadas.","ph":"fotos/p-harrods.jpg","cr":"Foto: user: Sokkk y · domínio público · Wikimedia Commons","fonte":"demo"},
  {"id":"camden","n":"Camden Market","area":"camden","lat":51.541389,"lng":-0.146389,"d":"Camden é o bairro da música e da cultura alternativa, com mercados que vendem de roupa vintage a comida de rua de todo o mundo. Amy Winehouse morou e cantou aqui.","dica":"O Camden Lock Market, à beira do canal, é a parte mais bonita; vá pelo canal a pé a partir de Regent's Park.","ph":"fotos/p-camden.jpg","cr":"Foto: en:User:Grim23 · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"little-venice","n":"Little Venice","area":"camden","lat":51.52,"lng":-0.18,"d":"Little Venice é o ponto onde dois canais se encontram, com barcos-casa coloridos e cafés flutuantes. É um dos cantos mais tranquilos do centro.","dica":"Um barco turístico leva de Little Venice a Camden pelo canal em 50 minutos.","ph":"fotos/p-little-venice.jpg","cr":"Foto: Matthias v.d. Elbe · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"primrose","n":"Primrose Hill","area":"camden","lat":51.5394,"lng":-0.1606,"d":"Primrose Hill é uma colina de 63 metros ao norte do Regent's Park, com uma das vistas mais bonitas de Londres, de graça. O bairro em volta é de casas coloridas e cafés.","dica":"Suba no fim da tarde e leve algo para beber: a vista com o pôr do sol é um programa inteiro.","ph":"fotos/p-primrose.jpg","cr":"Foto: Louise Ireland · CC BY-SA 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"plataforma-934","n":"Plataforma 9¾ (King's Cross)","area":"kingscross","lat":51.5322,"lng":-0.124,"d":"A Plataforma 9¾ fica dentro da estação King's Cross: um carrinho de bagagem meio enfiado na parede, com cachecol voando, para a foto de quem é fã de Harry Potter.","dica":"A fila é organizada e tem fotógrafo oficial, mas você pode usar o seu celular de graça.","ph":"fotos/p-plataforma-934.jpg","cr":"Foto: Bert Seghers · CC0 · Wikimedia Commons","fonte":"demo"},
  {"id":"st-pancras","n":"St Pancras Renaissance Hotel","area":"kingscross","lat":51.53,"lng":-0.125278,"d":"O St Pancras Renaissance Hotel ocupa o prédio neogótico de 1873 da estação de trens, que quase foi demolido nos anos 1960. Hoje é um hotel e a estação dos trens para Paris.","dica":"Entre no saguão para ver a escadaria; e repare que o prédio aparece em Harry Potter como a estação King's Cross.","ph":"fotos/p-st-pancras.jpg","cr":"Foto: LepoRello · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"covent-garden","n":"Covent Garden","area":"westend","lat":51.5125,"lng":-0.1225,"d":"Covent Garden foi o mercado de frutas e flores de Londres por 300 anos e hoje é uma praça coberta com lojas, cafés e artistas de rua. A Royal Opera House fica na esquina.","dica":"Os artistas se apresentam na praça principal e no nível de baixo; fique uns minutos, vale a pena.","ph":"fotos/p-covent-garden.jpg","cr":"Foto: Diliff derivative work: SilkTork (talk) · CC BY 2.5 · Wikimedia Commons","fonte":"demo"},
  {"id":"neals-yard","n":"Neal's Yard","area":"westend","lat":51.5144,"lng":-0.1265,"d":"Neal's Yard é um pátio escondido perto de Covent Garden, com fachadas pintadas em cores fortes e lojinhas de produtos naturais. É um dos cantos mais fotografados do West End.","dica":"Entre pela Short's Gardens; é fácil passar reto sem ver a entrada.","ph":"fotos/p-neals-yard.jpg","cr":"Foto: Elisa.rolle · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"transport-museum","n":"London Transport Museum","area":"westend","lat":51.512,"lng":-0.1215,"d":"O Museu do Transporte de Londres conta a história do metrô, dos ônibus vermelhos e dos táxis pretos, com veículos originais em que se pode entrar. Fica na praça de Covent Garden.","dica":"Crianças até 17 anos não pagam e o ingresso de adulto vale por um ano.","ph":"fotos/p-transport-museum.jpg","cr":"Foto: User:Clithering · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"cutty-sark","n":"Cutty Sark","area":"greenwich","lat":51.482778,"lng":-0.009722,"d":"O Cutty Sark é um veleiro de 1869 que transportava chá da China e lã da Austrália, um dos mais rápidos da sua época. Hoje está em exposição em Greenwich, suspenso para ser visto por baixo.","dica":"A visita por baixo do casco de cobre é a parte mais surpreendente.","ph":"fotos/p-cutty-sark.jpg","cr":"Foto: Ethan Doyle White · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"naval-college","n":"Old Royal Naval College","area":"greenwich","lat":51.483611,"lng":-0.005833,"d":"O Old Royal Naval College é um conjunto barroco de Christopher Wren à beira do rio, em Greenwich. O Painted Hall tem um teto pintado tão grande que foi chamado de \"Capela Sistina britânica\".","dica":"Os jardins e a capela são gratuitos; o Painted Hall é pago.","ph":"fotos/p-naval-college.jpg","cr":"Foto: Dmitry Tonkonog · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"observatorio","n":"Observatório Real e o Meridiano","area":"greenwich","lat":51.477,"lng":-0.0147,"d":"O Observatório Real de Greenwich é onde passa o meridiano zero, a linha que divide os hemisférios leste e oeste do planeta e marca a hora mundial. Fica no alto do parque.","dica":"Dá para pôr um pé em cada hemisfério na linha do pátio, mas a fila é grande; a mesma linha continua grátis do lado de fora.","ph":"fotos/p-observatorio.jpg","cr":"Foto: autor no Wikimedia Commons · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"windsor-castle","n":"Castelo de Windsor","area":"windsor","lat":51.4839,"lng":-0.6044,"d":"O Castelo de Windsor é o castelo habitado mais antigo e maior do mundo, residência de fim de semana do monarca há mais de 900 anos. Quando o rei está, a bandeira real tremula na torre redonda.","dica":"Fecha às terças e quartas em parte do ano; confira o site oficial antes.","ph":"fotos/p-windsor-castle.jpg","cr":"Foto: Diliff · CC BY 2.5 · Wikimedia Commons","fonte":"demo"},
  {"id":"st-georges","n":"Capela de St. George","area":"windsor","lat":51.483611,"lng":-0.606944,"d":"A Capela de São Jorge, dentro do castelo de Windsor, é onde foram enterrados Henrique VIII e a Rainha Elizabeth II, e onde Harry e Meghan se casaram em 2018.","dica":"Fecha aos domingos para os turistas; só quem vai à missa entra.","ph":"fotos/p-st-georges.jpg","cr":"Foto: autor no Wikimedia Commons · CC BY-SA 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"dolls-house","n":"Casa de Bonecas da Rainha Mary","area":"windsor","lat":51.4839,"lng":-0.6044,"d":"A Casa de Bonecas da Rainha Mary é uma miniatura perfeita de 1924, em escala 1:12, com luz elétrica, água corrente e livros escritos à mão por autores famosos.","dica":"Fica na rota da visita do castelo; crianças ficam hipnotizadas.","ph":"fotos/p-dolls-house.jpg","cr":"Foto: Rob Sangster · CC BY-SA 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"long-walk","n":"The Long Walk","area":"windsor","lat":51.48,"lng":-0.6,"d":"A Long Walk é a alameda reta de 4,2 km que liga o castelo de Windsor à estátua do Rei George III, no alto de uma colina do Grande Parque. Foi plantada no século XVII.","dica":"Caminhe só os primeiros 500 metros e vire para trás: é a melhor foto do castelo.","ph":"fotos/p-long-walk.jpg","cr":"Foto: Len Williams · CC BY-SA 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"eton","n":"Eton College","area":"windsor","lat":51.492,"lng":-0.608,"d":"Eton College é a escola fundada em 1440 que formou 20 primeiros-ministros britânicos e os príncipes William e Harry. Fica a 15 minutos a pé do castelo, do outro lado do rio.","dica":"A rua principal de Eton tem lojas de uniformes e casas de chá que parecem de outro século.","ph":"fotos/p-eton.jpg","cr":"Foto: Martin Kraft · CC BY-SA 3.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"harry-potter","n":"Estúdio Harry Potter (Warner Bros.)","area":"fora","lat":51.693333,"lng":-0.419722,"d":"O Warner Bros. Studio Tour, em Leavesden, mostra os cenários originais dos filmes de Harry Potter: o Grande Salão, o Beco Diagonal e o Expresso de Hogwarts. Fica a cerca de uma hora de Londres.","dica":"Esgota com meses de antecedência, principalmente nas férias; compre assim que tiver as datas.","ph":"fotos/p-harry-potter.jpg","cr":"Foto: S. Perquin · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"oxford","n":"Oxford — Radcliffe Camera","area":"fora","lat":51.7534,"lng":-1.2539,"d":"Oxford abriga a universidade de língua inglesa mais antiga do mundo, com colégios do século XIII. A Radcliffe Camera, a Bodleian Library e o Christ Church aparecem em Harry Potter.","dica":"O Christ Church fecha para visitantes em horários de aula; confira antes de ir.","ph":"fotos/p-oxford.jpg","cr":"Foto: Diliff · CC BY 2.5 · Wikimedia Commons","fonte":"demo"},
  {"id":"bath","n":"Termas romanas de Bath","area":"fora","lat":51.3809,"lng":-2.3595,"d":"Bath é a cidade das termas romanas de dois mil anos e das casas georgianas em pedra cor de mel, Patrimônio Mundial da UNESCO. Jane Austen morou aqui.","dica":"As termas romanas levam duas horas; o Royal Crescent é a foto da cidade.","ph":"fotos/p-bath.jpg","cr":"Foto: Diliff · CC BY 2.5 · Wikimedia Commons","fonte":"demo"},
  {"id":"stonehenge","n":"Stonehenge","area":"fora","lat":51.178889,"lng":-1.826111,"d":"Stonehenge é o círculo de pedras de 5.000 anos na planície de Salisbury, erguido antes das pirâmides do Egito. Ninguém sabe ao certo para que servia.","dica":"Compre o ingresso com horário marcado; o ônibus do centro de visitantes até as pedras está incluído.","ph":"fotos/p-stonehenge.jpg","cr":"Foto: garethwiscombe · CC BY 2.0 · Wikimedia Commons","fonte":"demo"},
  {"id":"hampton-court","n":"Hampton Court Palace","area":"fora","lat":51.403333,"lng":-0.3375,"d":"Hampton Court Palace foi o palácio de Henrique VIII, às margens do Tâmisa, com cozinhas Tudor gigantes e o labirinto de sebes mais antigo da Inglaterra.","dica":"Vá de trem da estação Waterloo em 35 minutos, ou de barco no verão.","ph":"fotos/p-hampton-court.jpg","cr":"Foto: Tilman2007 · CC BY-SA 4.0 · Wikimedia Commons","fonte":"demo"}
];

const AREAS = {
  city: 'City of London', southbank: 'Southbank', westminster: 'Westminster', bloomsbury: 'Bloomsbury',
  mayfair: "Mayfair e St James's", westend: 'West End', kensington: 'Kensington e Hyde Park', camden: "Camden e Regent's Park",
  greenwich: 'Greenwich', windsor: 'Windsor', kingscross: "King's Cross", fora: 'Além de Londres',
};
function ponto(id) { return (typeof DB !== 'undefined' && DB && Array.isArray(DB.pontos) && DB.pontos.find(p => p.id === id)) || PONTOS.find(p => p.id === id) || null; }

if (typeof module !== 'undefined') module.exports = { PONTOS, AREAS, ponto };
